import "../style/globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { inter } from "@/utils/fonts"; 

export const metadata = {
  title: "Bread Bakery",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout;
